type Comment {
    id: Int
    avatar: String
    name: String
    isTop: Boolean
    content: String
    publishDate: String
    commentNum: Int
    pariseNum: Int
}

type Query {
    comments: [Comment]
}

type Mutation {
    parise(id: Int): Int
}